# Generated by Django 5.0 on 2024-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current',
            name='name',
        ),
        migrations.RemoveField(
            model_name='current',
            name='offer',
        ),
        migrations.AddField(
            model_name='current',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='current',
            name='dietary_preference',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='current',
            name='existing_health_condition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='current',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='current',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='current',
            name='lifestyle_preference',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='current',
            name='meal_portion_size',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='current',
            name='meals_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='current',
            name='physical_activity_level',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='current',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
